Repository OutSystems/outsystems-maps, pull requests merged in 2024-06, with the labels that each got.

#177 ROU-10780: fix Google Maps custom markers with scaled sizes
  src/Providers/Maps/Google/Marker/Marker.ts
Labels: bug, cla:yes

#179 ROU-0: rollback TypeScript and type doc versions
  package.json
Labels: bug, dependencies

#175 ROU-4725: [OSMaps] - Leaflet misbehavior when changing marker location after zooming out
  src/OSFramework/Maps/Feature/ICenter.ts
  src/Providers/Maps/Leaflet/Features/Center.ts
  src/Providers/Maps/Leaflet/OSMap/OSMap.ts
Labels: cla:yes
