Repository OutSystems/outsystems-maps, pull requests merged in 2025-02, with the labels that each got.

#191 ROU-11587: javaScript Causing Error Logs on Google Places
  src/Providers/Maps/Google/Constants/Constants.ts
  src/Providers/Maps/Google/SearchPlaces/SearchPlaces.ts
  src/Providers/Maps/Google/SharedComponents/ExternalModules.ts
Labels: bug

#192 ROU-11587_V2: javaScript Causing Error Logs on Google Places
  src/OSFramework/Maps/SearchPlaces/AbstractSearchPlaces.ts
  src/Providers/Maps/Google/SearchPlaces/SearchPlaces.ts
Labels: bug, automations

#194 ROU-11629: javaScript Causing Error Logs on Google Maps
  src/OSFramework/Maps/OSMap/AbstractMap.ts
  src/OSFramework/Maps/SearchPlaces/AbstractSearchPlaces.ts
  src/Providers/Maps/Google/OSMap/OSMap.ts
  src/Providers/Maps/Google/SearchPlaces/SearchPlaces.ts
  src/Providers/Maps/Google/SharedComponents/ExternalModules.ts
  src/Providers/Maps/Google/SharedComponents/MapsAndSearchPlaces.ts
Labels: bug

#196 ROU-11574: Update leaflet types
  package.json
Labels: Improvements, dependencies
